In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Catatan : Numpy merupakan library python yang digunakan untuk komputasi matriks.
Matplotlib merupakan library python untuk presentasi data berupa grafik atau plot.

In [24]:
dataset = pd.read_csv('Data-country.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [25]:
print(x)

[['Indonesia' 40.0 72000.0]
 ['Thailand' 25.0 48000.0]
 ['Singapura' 30.0 54000.0]
 ['Thailand' 38.0 62000.0]
 ['Singapura' 45.0 nan]
 ['Indonesia' 25.0 58000.0]
 ['Thailand' nan 50000.0]
 ['Indonesia' 48.0 79000.0]
 ['Singapura' 50.0 83000.0]
 ['Indonesia' 38.0 68000.0]]


In [26]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [27]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [29]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [30]:
print(x)

[[1.0 0.0 0.0 40.0 72000.0]
 [0.0 0.0 1.0 25.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 62000.0]
 [0.0 1.0 0.0 45.0 63777.77777777778]
 [1.0 0.0 0.0 25.0 58000.0]
 [0.0 0.0 1.0 37.666666666666664 50000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 38.0 68000.0]]


In [31]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [32]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [33]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [34]:
print(x_train)

[[0.0 0.0 1.0 37.666666666666664 50000.0]
 [0.0 1.0 0.0 45.0 63777.77777777778]
 [1.0 0.0 0.0 40.0 72000.0]
 [0.0 0.0 1.0 38.0 62000.0]
 [0.0 0.0 1.0 25.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 25.0 58000.0]]


In [35]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 38.0 68000.0]]


In [36]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [37]:
print(y_test)

[0 1]


In [38]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [39]:
print(x_train)

[[0.0 0.0 1.0 -0.10310134176192358 -1.212208253742289]
 [0.0 1.0 0.0 0.7217093923334674 -0.05816738261719184]
 [1.0 0.0 0.0 0.15933843726842828 0.6305344275703657]
 [0.0 0.0 1.0 -0.06560994475758737 -0.20707588211720462]
 [0.0 0.0 1.0 -1.5277744279266892 -1.379730315679803]
 [1.0 0.0 0.0 1.0591319653724909 1.2168616443516649]
 [0.0 1.0 0.0 1.2840803473985065 1.551905768226693]
 [1.0 0.0 0.0 -1.5277744279266892 -0.5421200059922328]]


In [40]:
print(x_test)

[[0.0 1.0 0.0 -0.96540347286165 -0.8771641298672609]
 [1.0 0.0 0.0 -0.06560994475758737 0.2954903036953376]]
